# Generated by Django 4.1.3 on 2022-11-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch2', '0002_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
    ]
