# Generated by Django 4.1.3 on 2022-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch2', '0003_rename_first_name_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
