# Generated by Django 4.1.3 on 2022-12-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch2', '0005_registration_delete_student_delete_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Registrations',
        ),
    ]
