# Generated by Django 4.1.3 on 2022-12-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch2', '0009_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch2.registrations')),
            ],
        ),
    ]
